version: '3'
services:
  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    environment:
      KEY: '${KEY}'
      SECRET: '${SECRET}'
      ADMIN_EMAIL: '${ADMIN_EMAIL}'
      ADMIN_PASSWORD: '${ADMIN_PASSWORD}'
      DB_CLIENT: 'pg'
      DB_HOST: '${DB_HOST}'
      DB_PORT: '${DB_PORT}'
      DB_DATABASE: '${DB_DATABASE}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'

      # Configurações essenciais
      HOST: '0.0.0.0'
      PORT: '8055'
      PUBLIC_URL: '${PUBLIC_URL}'
      CORS_ENABLED: 'true'
